version: '3.3'

services:
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_CREATE_TOPICS: "my_topic:1:1"
      HOSTNAME_COMMAND: "hostname -i"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://_{HOSTNAME_COMMAND}:9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: on-failure
    volumes:
      - kafka_data:/kafka
    depends_on:
      - zookeeper
    networks:
      - kafka
    ports:
      - "9092:9092"

  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - kafka

volumes:
  kafka_data:

networks:
  default:
  kafka:
